Host git.iax.lol pi5 wrt pbi
  ConnectTimeout 5

Host git.iax.lol
  User iax
  Port 222

Host pi5
  Hostname 192.168.7.5
  User iax
  # PermitLocalCommand yes
  # LocalCommand figlet Pi5 | lolcat -f

Host wrt
  Hostname 192.168.7.1
  User root

Host pbi
  Hostname 192.168.7.90
  User iax
