# Oracle Cloud Free Tier
Host ciax
  Hostname 150.136.80.154
  User opc
  ControlMaster auto
  ControlPersist 10m
  ControlPath ~/.ssh/conn_%r@%h:%p
  ServerAliveInterval 60
  ServerAliveCountMax 3
  LocalForward 4040 localhost:4040            # -L 4040:localhost:4040 
  RemoteForward 127.0.0.1:5000 localhost:5000 # -R 5000:localhost:5000 
  RemoteForward 127.0.0.1:8080 localhost:8080 # -R 8080:localhost:8080
