# vi: ft=conf

# === DEFAULT KEY ==============================================================
default-key DAC9D9C180E66CB4

# === BEHAVIOR =================================================================
no-emit-version
no-comments
keyid-format LONG
with-fingerprint
list-options   show-uid-validity
verify-options show-uid-validity

# === KEYSERVER ================================================================
keyserver hkps://keys.openpgp.org
keyserver-options include-revoked

# === CIPHERS ==================================================================
personal-cipher-preferences  AES256 AES192 AES
personal-digest-preferences  SHA512 SHA384 SHA256
cert-digest-algo SHA512
default-preference-list SHA512 SHA384 SHA256 AES256 AES192 AES ZLIB BZIP2 ZIP Uncompressed
