#!/usr/bin/env bash
RST="\e[0m"
GRE="\e[92m"
BLU="\e[34m"

SUDO_FILE="/etc/sudoers.d/$USER"
sudo test -f "$SUDO_FILE" && { echo -e " -${GRE}OK$RST- $SUDO_FILE" && exit 0; }

echo -e "Current user: ${GRE}$USER${RST}"

sudo -u root -H sh -c "echo '$USER ALL=(ALL) NOPASSWD:ALL' > $SUDO_FILE"
# echo 'Defaults env_keep = "http_proxy https_proxy ftp_proxy"' | sudo tee -a "$SUDO_FILE"

echo -e "Created ${GRE}$SUDO_FILE${RST}"
sudo chmod -v 0440 "$SUDO_FILE"
