#!/usr/bin/env bash
RST="\e[0m"
GRE="\e[92m"
BLU="\e[34m"

SUDOERS_LINUX_PATH="/etc/sudoers.d"

get_sudoers_path() {
  if [[ "$OSTYPE" == "darwin"* ]]; then
    echo "/private"
  else
    echo ""
  fi
}

create_user_file() {
  file_name="$1"
  sudo -u root -H sh -c "echo '$USER ALL=(ALL) NOPASSWD:ALL' > $file_name"
  # echo 'Defaults env_keep = "http_proxy https_proxy ftp_proxy"' | sudo tee -a "$file_name"
  sudo chmod -v 0440 "$file_name"
}

FILE="$SUDOERS_LINUX_PATH/$USER"
sudo test -f "$FILE" && { echo -e " -${GRE}OK$RST- $FILE" && exit 0; }

echo -e "Current user: ${GRE}$USER${RST}"
prefix=$(get_sudoers_path)
create_user_file "$prefix$FILE"
echo -e "Created ${GRE}$FILE${RST}"
