#schema = "https://mise.jdx.dev/schema/mise.json"

# you can set these with `mise use -g`
[tools]
node = "lts"
python = "latest"
ruby = "latest"
usage = "latest"

[settings]
trusted_config_paths = ['~/dev', '~/projects']
yes = false # set to true to automatically answer yes to all prompts
idiomatic_version_file_enable_tools = ["ruby"]

[tasks.npm]
alias = "n"
description = "Upgrade npm and Install packages"
run = [
  "npm install -g npm",
  "npm install -g yarn npm-check-updates is-my-node-vulnerable npkill retire portless"
]

[tasks.gems]
alias = "g"
description = "Upgrade gem and Install gems"
run = [
  "gem update --system",
  "gem install bundler bundler-audit rails rubocop"
]

[tasks.pip]
alias = "p"
description = "Upgrade pip"
run = [
  "pip install --upgrade pip",
  "pip install --upgrade pipenv pip-audit"
]
